AWSTemplateFormatVersion: '2010-09-09'
Description: Api Gateway

Resources:
  OrdersApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: OrdersApi
      Description: Serverless API for order creation

  OrdersResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref OrdersApi
      ParentId: !GetAtt OrdersApi.RootResourceId
      PathPart: orders

  OrdersPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref OrdersApi
      ResourceId: !Ref OrdersResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateOrderFunction.Arn}/invocations
        
  OrdersLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref CreateOrderFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${OrdersApi}/*/POST/orders
      
  OrdersApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: OrdersPostMethod
    Properties:
      RestApiId: !Ref OrdersApi
      StageName: prod

